In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [2]:
data=pd.read_csv(r"C:\Users\DELL\Desktop\heart.csv")
data.head(n=2)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   

   ca  thal  target  
0   0     1       1  
1   0     2       1

In [26]:
real_x=data.iloc[:,[1,2,5,6,8,10,11,12]].values
real_y=data.iloc[:,13].values
real_x

array([[1, 3, 1, ..., 0, 0, 1],
       [1, 2, 0, ..., 0, 0, 2],
       [0, 1, 0, ..., 2, 0, 2],
       ...,
       [1, 0, 1, ..., 1, 2, 3],
       [1, 0, 0, ..., 1, 1, 3],
       [0, 1, 0, ..., 1, 1, 2]], dtype=int64)

In [34]:
train_x,test_x,train_y,test_y=train_test_split(real_x,real_y,test_size=0.3,random_state=0)

In [27]:
scaler=StandardScaler()
train_x=scaler.fit_transform(train_x)
test_x=scaler.fit_transform(test_x)
train_x

array([[ 0.73989544,  0.0315114 ,  2.28807651, ...,  0.955317  ,
        -0.69264875, -0.42921768],
       [ 0.73989544,  1.94020175,  2.28807651, ..., -0.67796691,
         0.29286491, -0.42921768],
       [ 0.73989544, -0.92283378, -0.43704832, ...,  0.955317  ,
         0.29286491,  1.13964695],
       ...,
       [ 0.73989544,  1.94020175, -0.43704832, ..., -0.67796691,
        -0.69264875,  1.13964695],
       [ 0.73989544,  0.98585657, -0.43704832, ...,  0.955317  ,
        -0.69264875, -0.42921768],
       [ 0.73989544,  0.0315114 , -0.43704832, ..., -0.67796691,
        -0.69264875, -0.42921768]])

In [15]:
NB1=BernoulliNB(binarize= True)
NB1.fit(train_x,train_y)

BernoulliNB(alpha=1.0, binarize=True, class_prior=None, fit_prior=True)

In [16]:
y_pred=NB1.predict(test_x)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0], dtype=int64)

In [19]:
c_m=confusion_matrix(test_y,y_pred)
c_m

array([[33, 11],
       [13, 34]], dtype=int64)

In [20]:
acc=accuracy_score(test_y,y_pred)
acc

0.7362637362637363

In [21]:
NB2=GaussianNB()
NB2.fit(train_x,train_y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [22]:
y_pred2=NB2.predict(test_x)
y_pred2

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0], dtype=int64)

In [23]:
c_m2=confusion_matrix(test_y,y_pred)
c_m2

array([[33, 11],
       [13, 34]], dtype=int64)

In [24]:
acc2=accuracy_score(test_y,y_pred)
acc2

0.7362637362637363

In [36]:
train_x,test_x,train_y,test_y=train_test_split(real_x,real_y,test_size=0.3,random_state=0)

In [37]:
NB1=MultinomialNB(alpha=1.0)
NB1.fit(train_x,train_y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [38]:
y_pred2=NB2.predict(test_x)
y_pred2

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [39]:
c_m3=confusion_matrix(test_y,y_pred)
c_m3

array([[33, 11],
       [13, 34]], dtype=int64)

In [40]:
acc2=accuracy_score(test_y,y_pred)
acc2

0.7362637362637363